version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: elt_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elt_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elt_network

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elt_extract_load
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: elt_database
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./etl_scripts:/app
    networks:
      - elt_network

  dbt:
    build:
      context: ./dbt_transform
      dockerfile: Dockerfile
    container_name: elt_dbt
    depends_on:
      etl:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: elt_database
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./dbt_transform:/usr/app
      - ./logs:/usr/app/logs
    networks:
      - elt_network

volumes:
  postgres_data:

networks:
  elt_network:
    driver: bridge
